[cookie]
expiry_days = 30

[cache_path]
path = 'data/cache/'

[credentials]
# admin arsenios
usernames = { test = { email = 'test@mail.com', name = 'test', password = 'test' }}

[preauthorized]
emails = ["test@mail.com"]

[local_db]
url = "data/db/local.db"

[queries]
client = 'queries/client.sql'
client_loans = 'queries/client_loans.sql'
client_offers = 'queries/client_offers.sql'

[gigachat_data]
auth_key = "GigaChat auth token"
client_secrets = "client secret"
client_id = "client id"

[model_auth]
url = "https://ngw.devices.sberbank.ru:9443/api/v2/oauth"
payload = 'scope=GIGACHAT_API_PERS'

[model_api]
url = "https://gigachat.devices.sberbank.ru/api/v1/models"
payload = { }

[model_answer_api]
url = "https://gigachat.devices.sberbank.ru/api/v1/chat/completions"
